name: Test with Maven
on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: 8
          java-distribution: temurin
      - name: Run tests with Maven
        run: mvn --batch-mode test
